#!/usr/bin/env python
'''
Print read names of orphan supplementary alignments (usually caused by dedup) in SAM file

Usage: findOrphan [<sam>]

Options:
    <sam>   input SAM, read from stdin if omitted
'''

from __future__ import print_function
import sys
import signal
import logging
signal.signal(signal.SIGPIPE, signal.SIG_DFL)
logging.basicConfig(
        level=logging.DEBUG,
        format='%(asctime)s; %(funcName)s; %(levelname)s; %(message)s',
        datefmt='%y-%m-%d %H:%M:%S')

SUPP = 0x800

def main(args):
    logging.info(args)
    samIn = args['sam']
    if samIn is None:
        stream = sys.stdin
    else:
        stream = open(samIn, 'r')
    primaryAlign = set()
    suppAlign = set()
    for line in stream:
        rname,flag,other = line.split('\t',2)
        flag = int(flag)
        if flag & SUPP:
            suppAlign.add(rname)
        else:
            primaryAlign.add(rname)
    stream.close()
    orphan = suppAlign - primaryAlign
    logging.info('primary: {}, supplementary: {}, orphan supplementary {}'.format(len(primaryAlign), len(suppAlign), len(orphan)))
    for rname in orphan:
        print(rname)


if __name__ == '__main__':
    from docopt import docopt
    args = docopt(__doc__)
    args = {k.lstrip('-<').rstrip('>'):args[k] for k in args}
    try:
        main(args)
    except KeyboardInterrupt:
        logging.warning('Interrupted')
        sys.exit(1)
